export const users = [
  {
    id: 1,
    name: "Mark Alexis Posadas",
    address: "123 Maple Street",
    hobbies: ["Reading", "Hiking", "Cooking"],
    age: 28,
    gender: "Male",
  },
  {
    id: 2,
    name: "Nes Ramos",
    address: "456 Oak Avenue",
    hobbies: ["Gaming", "Cycling"],
    age: 35,
    gender: "Female",
  },
  {
    id: 3,
    name: "Carmina Manuel",
    address: "789 Pine Road",
    hobbies: ["Photography", "Dancing"],
    age: 22,
    gender: "Female",
  },
  {
    id: 4,
    name: "Roxanne Garcia",
    address: "789 Pine Road",
    hobbies: ["Photography", "Dancing"],
    age: 22,
    gender: "Female",
  },
  {
    id: 5,
    name: "Melanie Castro",
    address: "789 Pine Road",
    hobbies: ["Photography", "Dancing"],
    age: 22,
    gender: "Female",
  },
  {
    id: 6,
    name: "Christine Joy Evangelista",
    address: "789 Pine Road",
    hobbies: ["Photography", "Dancing"],
    age: 22,
    gender: "Female",
  },
  {
    id: 7,
    name: "Virgilio Caranto",
    address: "789 Pine Road",
    hobbies: ["Photography", "Dancing"],
    age: 22,
    gender: "Male",
  },
];
